export const messageConfig = {
  greeting: [
    "Dear {owner},",
    "Hello {owner},",
    "Hi {owner},",
    "Good Morning {owner},",
    "Good Afternoon {owner},",
    "Good Evening {owner},",
    "Namaste {owner},",
    "Respected {owner},",
    "Dear Mr/Ms {owner},",
  ],

  wellWisher: [
    "Hope you are doing well.",
    "Hope this message finds you well.",
    "Hope you're having a good day.",
    "Hope all is well at your end.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],

  reminder: [
    "This is a reminder that your vehicle insurance is expiring on {expiryDate}.",
    "This is a reminder that your insurance renewal date is on {expiryDate}.",
    "This is a reminder that your policy expires on {expiryDate}.",
    "Just a heads up that your insurance is due for renewal on {expiryDate}.",
    "Friendly reminder that your insurance expires on {expiryDate}.",
    "Please note that your insurance is due for renewal on {expiryDate}.",
    "Quick reminder — your insurance expires on {expiryDate}.",
    "Your insurance expires on {expiryDate} — this is a reminder.",
  ],

  vehicle: [
    "Vehicle ({make} {model}, Reg: {vehicle})",
    "Vehicle: {make} {model} ({vehicle})",
    "Vehicle No. {vehicle} ({make} {model})",
    "Regarding your {make} {model} - {vehicle}",
    "For your vehicle: {make} {model} ({vehicle})",
    "Vehicle Register: {vehicle} ({make} {model})",
    "Vehicle (Reg: {vehicle})",
  ],

  renewal: [
    "Please contact us to renew your policy and stay protected.",
    "Please get in touch to continue your insurance.",
    "To stay covered, please renew before expiry.",
    "Contact us if you need a quotation.",
    "We request you to renew it at the earliest.",
    "We will be happy to assist with your renewal.",
    "Kindly renew at the earliest to avoid a lapse.",
    "Please reach out to us for a quick renewal.",
  ],

  documents: [
    "Also, kindly share RC copy, Insurance copy, Aadhaar and PAN card.",
    "Please send us your RC, Insurance copy, Aadhaar and PAN.",
    "Kindly WhatsApp your RC and Insurance documents along with Aadhaar and PAN.",
    "Please share the required renewal documents: RC, Insurance copy, Aadhaar card and PAN card.",
    "Could you please share your RC, Insurance copy, Aadhaar card and PAN?",
    "Please share your RC copy, Insurance copy, Aadhaar card and PAN card.",
    "Please share the needed documents: RC, Insurance, Aadhaar and PAN.",
    "Kindly share the documents: RC copy, Insurance copy, Aadhaar and PAN.",
  ],

  closing: [
    "Thank you.",
    "Thanks.",
    "Regards, Insurance Team",
    "Regards, 247 Insurance Agency",
    "Warm regards, Insurance Team",
    "Thank you, Insurance Team",
    "Best regards, Insurance Team",
    "Regards, Your Insurance Partner",
  ],
};
